# Ğ¡Ğ¾Ğ·Ğ´Ğ°Ñ‚ĞµĞ»ÑŒ ÑĞºÑ€Ğ¸Ğ¿Ñ‚Ğ°: https://vk.com/ferius_057
# ğ“ğ“·ğ“µğ“²ğ“·ğ“®ğ“£ğ“¸ğ“¢ğ“½ğ“ªğ“½ğ“¾ğ“¼
configVersion: 2.0


# ĞŸĞ¾Ğ´Ñ€Ğ¾Ğ±Ğ½ÑƒÑ Ğ¸Ğ½Ñ„Ğ¾Ñ€Ğ¼Ğ°Ñ†Ğ¸Ñ Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ Ğ¿Ğ¾Ğ»ÑƒÑ‡Ğ¸Ñ‚ÑŒ Ğ² Ñ„Ğ°Ğ¹Ğ»Ğµ help.yml
vk:
  group_id: "200934694"
  user_token: "token"
minecraft:
  ip: "ip"
  port: 25565
delay: 60
statusText: "Online: %online% / %max_online% {%growth%} Hour: {%growth_hour%}, Ğ ĞµĞºĞ¾Ñ€Ğ´ Ğ¾Ğ½Ğ»Ğ°Ğ¹Ğ½Ğ° Ğ·Ğ° Ñ‡Ğ°Ñ: {%record_hour%} | ĞĞ±Ñ‰Ğ¸Ğ¹ Ñ€ĞµĞºĞ¾Ñ€Ğ´ Ğ¾Ğ½Ğ»Ğ°Ğ¹Ğ½Ğ°: {%record_all%} | %time%"
time_format: "dd.MM.yyyy HH:mm:ss"
